version: '3'
services:
  app:
    build: .
    image: backend-test
    ports:
      - "3301-3304:3301-3304"
    command: ["node", "server.js"]
    env_file:
      - .env
      - .env.testing
    network_mode: "host"